version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway" # Can access localhost
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: kotlindb # Default maintenance database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
